### ISSUE TITLE
"Pin to taskbar" not working on Windows 10

### ISSUE THREAD

**Issue by steelywing** [lordmulder/stdutils#10]
I use the `InvokeShellVerb` sample but `${StdUtils.InvokeShellVerb}` return `not_found`.
Env:
- Windows 10
- NSIS 3 Unicode

**Comment by lordmulder** [comment]
The plug-in has not been tested with NSIS 3 yet, did you try with Unicode NSIS v2.46.5?
http://www.scratchpaper.com/

Furthermore, error `not_found` indicates that the file you are trying to pin has **not** been found...

**Comment by lordmulder** [comment]
Okay, I have debugged the problem today.

I turns out that if we enumerate the *ShellVerbs* of the target file via the Win32 API in **Windows 10**, then there simply is **no** "Pin to Taskbar" item - although if we right-click on the program file in Explorer, it definitely is there! Even more strange, the "Pin to Startmenu" verb *is* found.

**Comment by lordmulder** [comment]
Tried to implement a workaround. Please try this **TEST** build:
http://sourceforge.net/projects/muldersoft/files/StdUtils-Plugin%20%28NSIS%29/Testing/StdUtils.2015-09-23.zip/download

**Comment by steelywing** [comment]
Thanks, the __TEST__ build working :smiley:

**Comment by lordmulder** [comment]
Okay, I have just released a new version that has this change included.

**Comment by dsomesh** [comment]
I have similar requirements in my project. Earlier versions of my project used to pin to taskbar using enumerated  ShellVerbs. Now suddenly pin is nit happening for 32 bit windows 7 and windows 10 taskbar.What is the work-around for this?

**Comment by lordmulder** [comment]
Be sure to use *latest* plug-in version. Also be sure to use 
InvokeShellVerb function with one of the constants defined in StdUtils.h.

See here:
https://github.com/lordmulder/stdutils/blob/master/Include/StdUtils.nsh#L401

**Comment by dsomesh** [comment]
Thanks for the quick response.Can you pleaes be more generic on this.Actually we are  scanning the enumerated ShellVerbs of a lnk file and matching it with the verb passed(5386 in case of taskbar). All this are done in native code.If the enumrated verb itself is not there how can we execute the verb?

**Comment by lordmulder** [comment]
The InvokeShellVerb function does *not* take a Verb string. Nor does it 
take a Verb resource ID. Instead, it takes one of the constants defined 
in the StdUtils.nsh include file. The StdUtils plug-in takes care of all 
the rest internally. There are multiple different resource ID's we need 
to test (internally), but you don't need to worry about this.

For example:
${StdUtils.InvokeShellVerb} $0 "$SYSDIR" "mspaint.exe" 
${StdUtils.Const.ShellVerb.PinToTaskbar}

**Comment by lordmulder** [comment]
The InvokeShellVerb function does **not** take a Verb _string_. Nor does it take a Verb resource ID.

Instead, it takes one of the constants defined in the `StdUtils.nsh` include file. The StdUtils plug-in takes care of all the rest internally. There are multiple different resource ID's we need to test (internally), but you don't need to worry about this. For example, you can do something like this:

    ${StdUtils.InvokeShellVerb} $0 "$SYSDIR" "mspaint.exe" ${StdUtils.Const.ShellVerb.PinToTaskbar}
