### ISSUE TITLE
getParameter only allows alphanumeric characters

### ISSUE THREAD

**Issue by Marshallx** [lordmulder/stdutils#13]
If I try to get a parameter named "_secret" then it doesn't find it.
I checked the source code and it only allows alphanumeric?

**Comment by lordmulder** [comment]
Yes, currently parameter **name** is checked to be *alphanumeric*.

I can allow underscore (`_`) and minus (`-`) too, if you think that is required.

**Comment by Marshallx** [comment]
It would certainly be useful for me!
Although I'm also debating whether or not I should be supporting - and -- as a switch rather than /

**Comment by lordmulder** [comment]
I will see what I can do :smirk:

**Comment by lordmulder** [comment]
Please try with this **TEST** version:
[**StdUtils.2016-06-09.zip**](https://sourceforge.net/projects/muldersoft/files/StdUtils-Plugin%20%28NSIS%29/Testing/StdUtils.2016-06-09.zip/download)

**Comment by lordmulder** [comment]
No more answer, so I'm going to assume it's fine (or no longer relevant).
