### ISSUE TITLE
GetRealOsName should use GetOsEdition routines to give correct friendly name for newer Windows Server versions.

### ISSUE THREAD

**Issue by Nutzzz** [lordmulder/stdutils#16]
GetRealOsName should use GetOsEdition routines to give correct friendly name for newer Windows Server versions.

i.e., if:
`OSVERSIONINFOEX.wProductType != VER_NT_WORKSTATION`

then:
10.0 --> "Windows Server 2016"
6.3 --> "Windows Server 2012 R2"
6.2 --> "Windows Server 2012"
6.1 --> "Windows Server 2008 R2"
6.0 --> "Windows Server 2008"
5.2 --> "Windows Server 2003"

Note that Win2K3 and Win2K3 **R2** are both 5.2.3790 (as is WinXP x64).  I personally think it'd be fine for GetRealOsName to not differentiate between 2003 and 2003 R2, but apparently you can tell the difference in that 2K3 is: `GetSystemMetrics(SM_SERVERR2) == 0` and 2K3 R2 is: `GetSystemMetrics(SM_SERVERR2) != 0`

**Comment by Nutzzz** [comment]
I guess there's also 5.0 "Windows 2000 Server" (note that "Server" and "2000" are in the opposite order from later releases)

**Comment by Nutzzz** [comment]
@lordmulder : I see you fulfilled my other issue.  Figured I'd send you what I had for this one.
[GetRealOsName.zip](https://github.com/lordmulder/stdutils/files/483360/GetRealOsName.zip)

**Comment by lordmulder** [comment]
`GetRealOsName` will consider the *edition* now. See here for details:
https://github.com/lordmulder/stdutils/blob/0ec9f2b25c9e3906adfc2f392b777f1c6b3e9324/Contrib/StdUtils/src/DetectOsVersion.cpp#L305-L313

**Comment by Nutzzz** [comment]
Works for me, though the "Windows XP (Server)" string is odd %-) (I put "error" in my version).
