### ISSUE TITLE
"/?" command line parameter

### ISSUE THREAD

**Issue by Nutzzz** [lordmulder/stdutils#17]
I'd like GetParameter to be able to recognize "/?" as a command line parameter.

However,
`${StdUtils.GetParameter} $0 "?" "no"`
doesn't work,  since "?" doesn't start with a letter, number, or underscore.

Perhaps line 134 of ParameterParser.cpp could changed from:
`if(arg_offset && arg_offset[0] && (ISALNUM(arg_offset[0]) || (arg_offset[0] == T('_'))))`
to:
`if(arg_offset && arg_offset[0] && (ISALNUM(arg_offset[0]) || (arg_offset[0] == T('_')) || (arg_offset[0] == T('?'))))`

**Comment by lordmulder** [comment]
I decided to implement a more generalized solution.

You can now use **any** character in parameter name, except for equality sign (`=`).

New **TEST** build is available now:
[StdUtils.2016-09-20.zip](https://sourceforge.net/projects/muldersoft/files/StdUtils-Plugin%20%28NSIS%29/Testing/StdUtils.2016-09-20.zip/download)

**Comment by Nutzzz** [comment]
I like the idea of a generalized solution, but GetParameter still isn't recognizing /? with  `${StdUtils.GetParameter} $0 "?" "no"`
Do I need to escape it in some way for the parser?

**Comment by lordmulder** [comment]
Works for me 😕 

Be aware that `${StdUtils.GetParameter}` returns the *default* value (in your case `"no"`) when the parameter is **not** specified on the command-line. If the parameter *is* specified on the command-line, then it returns the given value. For `setup.exe /?` this would be the *empty* string (`""`), as **no** value is given! If you want `"yes"` as result, you have pass `setup.exe /?=yes`.

Please try with a code like this:

	Section
		${StdUtils.TestParameter} $R0 "?"
		StrCmp "$R0" "true" 0 +3
		DetailPrint 'Command-line parameter /? is specified!'
		Goto +2
		DetailPrint 'Command-line parameter /? is *not* specified!'
		
		${StdUtils.GetParameter} $R0 "?" "<MyDefault>"
		DetailPrint 'Value of command-line parameter /? is: "$R0"'
	SectionEnd

**Comment by Nutzzz** [comment]
Right.  I've got an
`${IfNot} $0 == "no"`
statement (I'm using LogicLib).  I certainly could use TestParameter instead, but several of my other parameters take subparameters, and I found it easier to keep a consistent format.

I don't think I have a logic issue in my script, as I can substitute "H" for "?" and then "/H" works without issue...

Thanks for your help.

**Comment by lordmulder** [comment]
I still think you should be using `${StdUtils.TestParameter}` to check for the **presence** of a parameter.

Your test would fail for `setup.exe /?=no`. At least use an unlikely default like `"!§$%&666"`.

Anyhow, are you sure you are *really* using the **latest** build of the StudUtils DLL? Looks all good for me:
http://i.imgur.com/kiiJhyo.jpg

**Comment by Nutzzz** [comment]
I don't dispute that.  I am indeed using the latest, and after changing to TestParameter, it now works, so... that's good enough for me! Thanks. 👍
