### ISSUE TITLE
Command Line Parameter of form "/-X" is not recognized

### ISSUE THREAD

**Issue by Nutzzz** [lordmulder/stdutils#20]
After #17's generalized solution (thanks again), I can't get a parameter of the form "/-X" to be recognized by GetParameter or TestParameter:
e.g.,
`${StdUtils.TestParameter} $R0 "-p"`
gives "false" for $R0 even if "/-p" is on the command line.  Likewise,
`${StdUtils.GetParameter} $R1 "-p" "default"`
gives "default" for $R1 rather than "".  Indeed, "/-p=test" gives "default" as well.

**Comment by Nutzzz** [comment]
I just remembered that the user can give "--" as an alternative for "/".  It must be related...

**Comment by lordmulder** [comment]
A valid parameter name must **not** _start_ with a hyphen (`-`), slash (`/`) or backslash (`\`) character. Apart from that, any [*graphical*](http://en.cppreference.com/w/cpp/string/byte/isgraph) character is allowed in the parameter name now, except for the equal sign (`=`).

*Note:* The **`--`** or **`/`** prefix is **not** a part of the parameter name! Consequently, if you specify in your script `${StdUtils.GetParameter} $R1 "foo" "default"`, then either `/foo=bar` or `--foo=bar` will work :smirk:

**Comment by Nutzzz** [comment]
Right... I guess I'll use "/!p"  😁

Thanks!
