### ISSUE TITLE
x64 builds

### ISSUE THREAD

**Issue by develar** [lordmulder/stdutils#24]
Could you please also distribute plugin for x64?

**Comment by lordmulder** [comment]
Sorry, not at this time. The plug-in is currently built against the NSIS v2.xx headers and import files. It may work or not with NSIS v3.xx (it probably does), but only with the 32-Bit (x86) edition.

There was **no** 64-Bit (x64) edition of the NSIS 3.xx. We'll get that, if I ever make the transition to NSIS 3.xx.
